### ISSUE TITLE
static routing page

### ISSUE THREAD

**Issue by feckert** [jow-/luci-ng#19]
@jow- I am working on a static routing page. And i am using your l2.cbi.js class for the first time.
I have added the related options and the save button works. luci2 calls the uci add rpcd works as expected and i can see this witch `ubus call uci changes '{"config":"network"}'`

During development i have notices mybe some problems with the rpcd uci call back.

- An `ubus call uci changes"`shows my changes i have made with luci2

- An `ubus call uci commit` saves the changes to the /etc/config/network

- Another `ubus call uci changes` shows already the changes i have made previously? I would expect that the output is empty?

- And an `ubus call uci revert` after the luci2 add call does not work as expected? The change is already shown I can not revert?

- And if i do another `ubus call uci commit` i see the last entry twice. I have added with luci2?

What is the problem? Or do i do something wrong

Kind Regards

Flo

**Comment by jow-** [comment]
Usually each login session uses a different uci staging directory so you shouldn't see changes made by LuCI on the cli. Are you sure that you didn't actually do the same changes twice? Once on the cli for testing and once on the ui or something like that?

**Comment by feckert** [comment]
@jow- Sorry for the noice :-).

I did not know recognized, that there is a separate staging area  for every ubu_rpc_session.
