### ISSUE TITLE
Luci-ng general

### ISSUE THREAD

**Issue by feckert** [jow-/luci-ng#36]
A lot of changes where made since my last check.
I pulled in the last changes and build a new luci-ng packages.
I could log in, but i could not change the page. I always get overview page if i push the menu links.
**Do I miss something?**

**Comment by ianchi** [comment]
Hi @feckert, I've just commited many more changes. (you can take a look at PR #35)
It includes a complete rework of the menu and navigation.
It would be great if you can help testing it.

**Comment by feckert** [comment]
Hi @lanchi thanks for reply. I am now testing it, and try to understand your changes :-). 
The first lock and feel is great. Go on

**Comment by feckert** [comment]
Hallo @ianchi I tested your changes. But actually the "network/route" and the other uci/cbi pages does not working anymore as expected.

**Failure:**
The routing rules will not display and i also can not add new rules only the 'config route' in '/etc/config/network' will be set.

**Questions:**
Does this have to do with angular "matrial"?
Ar there further changes planed in cbi?

**Comment by ianchi** [comment]
Certainly many changes are pending to cbi but in the meantime this should still work as before.
I'll take a look at it as soon as I can.
I appreciate your reports and help testing.

**Comment by ianchi** [comment]
@feckert, a question, does it simple don't save changes or do you get into a login loop?

**Comment by ianchi** [comment]
After some digging I think there are (at least) two problems that go back to this commit https://github.com/jow-/luci-ng/commit/7487b57fb8cd8845e75627c6a2577b77c054d411 when I splited cbi directives in code + template and started using transclusion.
- one problem is a syntax error on the template on cbiNetworkList, which I'll fix asap. This was causing the control not to render
- there is a deeper problem, introduced with the switch to transclusion. Now scopes don't inherit in the same way cbiOption supposes, and so sections can't be saved. This is more complex to solve, and as cbi is undergoing a rebumping, I don't know if it is worth the effort. I'll see if I can figure out some work arround for the meantime.

**Comment by feckert** [comment]
@lanchi If I press save, then the page will gray out and nothing happens.
Could this have todo with this line?
https://github.com/jow-/luci-ng/blob/master/luci2-ui-base/src/www/luci-ng/cbi/cbiMap.js#L62
The function "self.read" is not defined?

**Comment by ianchi** [comment]
@feckert, I've just pushed a fix for the above problems:
- transclusion/scopes problems that were preventing to save changes: temporary revert the use of templates+transclusion, till a deeper rework of cbi is done
- readded cbiMap.read() to complete the save path, and remove the "disabled" state, which left the page grayed out
- fix syntax error in NetworkList, which was preventing it from displaying.

I'd appreciate if you can do some more thorough tests, to be sure all cases are covered.
As you can see, we are currently in the middle of some heavy changes (many with side effects), and all your help in testing is very valuable.

By the way, as all these commits only involve client code, you don't need to continuously flash the router for testing. You can pull updates to your git repo, and then go to `luci2-ui-base/src` and run `gulp serve` (first you need to _prepare_ the instance, as explained in [BUILD.md](https://github.com/ianchi/luci-ng/blob/master/luci2-ui-base/docs/BUILD.md), in general this step is needed only once or if there are any new dependencies).
This will run a local server that forwards all ubus request to your router. Then you point your browser to `localhost:3000` and you'll get luci-ng as if you where on the router.
The port may vary if it is taken (it will be shown when running gulp). The address of your router must first be set in `src/gulp/conf.js`.

**Comment by feckert** [comment]
@ianchi I am working with x86_64 and lantiq_xrx200 since you have added the line "PKG_BUILD_DEPENDS:=node/host" i have problem to compile node for the host system on target lantiq_xrx200(mips24k). The Target x86_64 build is working as expected.

On Target lantiq_xrx200(mips24k) I always get the following errors during build

> g++ '-DGTEST_DONT_DEFINE_ASSERT_EQ=1' '-DGTEST_DONT_DEFINE_ASSERT_GE=1' '-DGTEST_DONT_DEFINE_ASSERT_GT=1' '-DGTEST_DONT_DEFINE_ASSERT_LE=1' '-DGTEST_DONT_DEFINE_ASSERT_LT=1' '-DGTEST_DONT_DEFINE_ASSERT_NE=1' -I../src -I../deps/v8/include -I../deps/gtest/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out/Release/.deps//home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out/Release/obj.target/cctest/test/cctest/util.o.d.raw -I/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/staging_dir/host/include -I/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/staging_dir/host/usr/include -I/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/staging_dir/target-mips_24kc_musl-1.1.16/host/include  -c -o /home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out/Release/obj.target/cctest/test/cctest/util.o ../test/cctest/util.cc
> make[6]: execvp: printf: Argument list too long
> deps/openssl/openssl.target.mk:862: recipe for target '/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out/Release/obj.target/deps/openssl/libopenssl.a' failed
> make[6]: *** [/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out/Release/obj.target/deps/openssl/libopenssl.a] Error 127
> make[6]: *** Waiting for unfinished jobs....
> make[6]: Leaving directory '/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/out'
> Makefile:45: recipe for target 'node' failed
> make[5]: *** [node] Error 2
> make[5]: Leaving directory '/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5'
> Makefile:93: recipe for target '/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/.built' failed
> make[4]: *** [/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/lede/build_dir/target-mips_24kc_musl-1.1.16/host/node-v4.4.5/.built] Error 2
> make[4]: Leaving directory '/home/bbslave/buildSlave/lede_dev_lantiq_xrx200/System6/build/feeds/packages/lang/node'
> 

I think the important line is
> make[6]: execvp: printf: Argument list too long

I already opened a ticket on lede with this issue

https://forum.lede-project.org/t/build-failure-for-node-v4-4-5-on-lede-17-01/1566

**Comment by ianchi** [comment]
It is strange as the host is the same for all targets.
This is something related to LEDE's build system, perhaps @jow- can help us here.

If you already have node globally installed in your host, you could remove the host dependency altogether.
It is added to be sure that the proper tools are present in the build environmet. Perhaps we could automate this and only add the dependency if nodejs is not already globally installed in the system.

**Comment by feckert** [comment]
@ianchi i have solved my issue with node.
But i had to patch the sources witch small changes with this patch https://github.com/nodejs/node/pull/9141 from @NeoRaider.

**Comment by ianchi** [comment]
Great!
Was the original problem with saving on LUCI-NG solved after the fix I pushed?

**Comment by feckert** [comment]
@ianchi thanks for the fast fix :-) it is working again

**Comment by feckert** [comment]
Backup functionality is not working anymore.
I always get an "backup.tar.gz" with 33Bytes.

The same for Upgrade i could not upload a file.
Output "Web Console"
> Unknown provider: $modalProvider <- $modal <- SystemSoftwareController <-

**Comment by ianchi** [comment]
Ups!
The upgraded Angular Boostrap version changed module prefixes (now it is $uibModal instead of $modal). Some time back I changed all references in the "core" files, but obviouslly left some of the "views" controllers out...
Will complete the change asap (this is temporary, as in the middle run we plan to drop Boostrap library).

Again, thanks for your testing, it is very much appreciated (and needed).

**Comment by ianchi** [comment]
Hi @feckert, I've pushed a fix. Pleas confirm that it is working.
