### ISSUE TITLE
What is a status of the project?

### ISSUE THREAD

**Issue by stokito** [jow-/luci-ng#54]
The only information about the project is only the wiki page https://openwrt.org/docs/techref/luci2
The idea looks really nice. I have a small router with limited memory and the idea of getting rid off the Lua interpreter looks interesting for me.
Do you have any plans and willing to continue the project?

**Comment by zhaojh329** [comment]
https://github.com/zhaojh329/oui

**Comment by cricket007** [comment]
https://openwrt.org/releases/19.07/notes-19.07.2#client-side_rendering_of_the_luci_web_interface

**Comment by stokito** [comment]
thank you, now it's more clear
